
package ua.nure.book.server.service;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import ua.nure.book.entity.Book;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://book.nure.ua/server/service")
@XmlSeeAlso({
    ua.nure.book.entity.ObjectFactory.class,
    ua.nure.book.server.service.ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @param bookId
     * @throws DAOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeBook", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.RemoveBook")
    @ResponseWrapper(localName = "removeBookResponse", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.RemoveBookResponse")
    @Action(input = "http://book.nure.ua/server/service/BookService/removeBookRequest", output = "http://book.nure.ua/server/service/BookService/removeBookResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://book.nure.ua/server/service/BookService/removeBook/Fault/DAOException")
    })
    public void removeBook(
        @WebParam(name = "bookId", targetNamespace = "")
        int bookId)
        throws DAOException_Exception
    ;

    /**
     * 
     * @param book
     * @return
     *     returns int
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.AddBookResponse")
    @Action(input = "http://book.nure.ua/server/service/BookService/addBookRequest", output = "http://book.nure.ua/server/service/BookService/addBookResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://book.nure.ua/server/service/BookService/addBook/Fault/DAOException")
    })
    public int addBook(
        @WebParam(name = "Book", targetNamespace = "http://book.nure.ua/entity")
        Book book)
        throws DAOException_Exception
    ;

    /**
     * 
     * @param book
     * @throws DAOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "editBook", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.EditBook")
    @ResponseWrapper(localName = "editBookResponse", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.EditBookResponse")
    @Action(input = "http://book.nure.ua/server/service/BookService/editBookRequest", output = "http://book.nure.ua/server/service/BookService/editBookResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://book.nure.ua/server/service/BookService/editBook/Fault/DAOException")
    })
    public void editBook(
        @WebParam(name = "Book", targetNamespace = "http://book.nure.ua/entity")
        Book book)
        throws DAOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ua.nure.book.entity.Book>
     */
    @WebMethod
    @WebResult(name = "bookList", targetNamespace = "http://book.nure.ua/entity")
    @RequestWrapper(localName = "listBooks", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.ListBooks")
    @ResponseWrapper(localName = "listBooksResponse", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.ListBooksResponse")
    @Action(input = "http://book.nure.ua/server/service/BookService/listBooksRequest", output = "http://book.nure.ua/server/service/BookService/listBooksResponse")
    public List<Book> listBooks();

    /**
     * 
     * @param bookId
     * @return
     *     returns ua.nure.book.entity.Book
     * @throws DAOException_Exception
     */
    @WebMethod
    @WebResult(name = "Book", targetNamespace = "http://book.nure.ua/entity")
    @RequestWrapper(localName = "takeBook", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.TakeBook")
    @ResponseWrapper(localName = "takeBookResponse", targetNamespace = "http://book.nure.ua/server/service", className = "ua.nure.book.server.service.TakeBookResponse")
    @Action(input = "http://book.nure.ua/server/service/BookService/takeBookRequest", output = "http://book.nure.ua/server/service/BookService/takeBookResponse", fault = {
        @FaultAction(className = DAOException_Exception.class, value = "http://book.nure.ua/server/service/BookService/takeBook/Fault/DAOException")
    })
    public Book takeBook(
        @WebParam(name = "bookId", targetNamespace = "")
        int bookId)
        throws DAOException_Exception
    ;

}
